apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-main
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/app/overlays/ephemeral-instances
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
