apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  strategy: {}
  template:
    spec:
      containers:
      - name: nginx
        resources: 
          requests:
            memory: "128Mi"
            cpu: "250m"
