name: create-ephemeral
on:
  issue_comment:
    types: [created]
jobs:
  commit-flux-sync:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy-ephemeral')
    
    steps:
    - name: Get PR branch
      uses: xt0rted/pull-request-comment-branch@v2
      id: comment-branch
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Generate Flux Manifests
      run: ./scripts/create-env.sh ${{ steps.comment-branch.outputs.head_ref }}
    - name: Commit Changes
      uses: EndBug/add-and-commit@v9
      with:
        add: '.'
        message: "[ci skip] ephemeral env from ${{ steps.comment-branch.outputs.head_ref }}"
    - name: Set Commit Status
      uses: myrotvorets/set-commit-status-action@master
      if: always()
      with:
        sha: ${{ steps.comment-branch.outputs.head_sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
