name: destroy-ephemeral
on:
  issue_comment:
    types: [created]
  pull_request:
    types:
      - closed
jobs:
  delete-flux-sync:
    if: |
      (github.event.pull_request.merged == true) || 
      (github.event.issue.pull_request && contains(github.event.comment.body, '/destroy-ephemeral'))
    runs-on: ubuntu-latest
    steps:
    - name: Set commit status as pending
      uses: myrotvorets/set-commit-status-action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        status: pending
    - name: Get PR branch
      uses: xt0rted/pull-request-comment-branch@v2
      id: comment-branch
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Delete Flux Manifests
      run: rm -rf ./k8s/app/overlays/ephemeral-instances/sync-${{ steps.comment-branch.outputs.head_ref }}.yaml
    - name: Commit Changes
      uses: EndBug/add-and-commit@v9
      with:
        add: '.'
        message: "[ci skip] destroy ephemeral env from ${{ steps.comment-branch.outputs.head_ref }}"
        default_author: github_actions
    - name: Set Commit Status
      uses: myrotvorets/set-commit-status-action@master
      if: always()
      with:
        sha: ${{ steps.comment-branch.outputs.head_sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
